---
title: "Data Analytics - Sampling Table"
author: "Rafael Garcia"
subtitle: "Passcode problem"
date: '2022'
output:
  pdf_document: default
  html_document:
    df_print: paged
---

## Libraries
```{r}
install.packages("gtools");
```

# Passcodes have 4 digits, ranging from 0 to 9.
## a) Possible passcodes
```{r}
dim(gtools::permutations(n = 6, r = 4, repeats.allowed = TRUE))[1]
```

## b) Unique passcodes, 4 distinct digits, repetition not allowed
```{r}
dim(gtools::permutations(n = 6, r = 4, repeats.allowed = FALSE))[1]
```

## c) Ascending passcode, repetition allowed
```{r}
uniques = gtools::permutations(n=6, r=4, repeats.allowed = FALSE);

uniques.ascending = apply(uniques, 1, function(x) sort(x));
uniques.ascending = t(uniques.ascending);
uniques.ascending = data.frame(uniques.ascending);

dim(unique(uniques.ascending))[1]
```

## d) Ascending, but not unique
```{r}
passcodes = gtools::permutations(n=6, r=4, repeats.allowed=TRUE);

ascending = apply(passcodes, 1, function(x) sort(x));
ascending = t(ascending);
ascending = data.frame(ascending);

dim(unique(ascending))[1]
```

## 
```{r}
#generate the committees (people labeled 1 to 5)
committees2 = gtools::combinations(n = 3, r = 2)
committees1 = gtools::combinations(n = 3, r = 1)

#print the sets of the two committees
committees2; committees1
```

$$
 \frac{kn!}{k! * (n-k)!}
$$
```{r}
#label people 1 to 4
people = 1:4

#first, we do the president-first approach
#initialize the committees
committees1 = character(0)

#iterate through potential presidents
for(i in 1:length(people)){
  
  #generate the new committes, with i as the president
  new.committees = cbind(i, gtools::combinations(n = length(people) - 1, r = 2, v = people[-i]))
  
  #add on to existing committees
  committees1 = rbind(committees1, new.committees)
}

  
#remove column names
colnames(committees1) = c("", "", "")



#second, we do the committee-first approach; initialize here
committees2 = character(0)

#generate all of the committees, without presidents
new.committees = gtools::combinations(n = 4, r = 3)

#iterate through the committees and add presidents
for(i in 1:dim(new.committees)[1]){
  
  #pick each person as president
  for(j in 1:3){
    
    #add the committee
    committees2 = rbind(committees2, c(new.committees[i, j], new.committees[i, -j]))
  
  }
}

#remove column names
colnames(committees2) = c("", "", "")

#print the two groups of committees; should be the same size
#   the first person is president in each case
#we should have k*choose(n, k) = 3*choose(4, 3) = 12 total
committees1; committees2;
```

```{r}
#replicate
set.seed(110)
sims = 1000

#create a deck; define spades as 1, everything else as 0
deck = c(rep(1, 13), rep(0, 52 - 13))

#keep track of the number of spades we sample
spades = rep(NA, sims)

#run the loop
for(i in 1:sims){
  
  
  #deal the four card hand
  hand = sample(deck, 4, replace = FALSE)
  
  #see how many spades we got
  spades[i] = sum(hand)
}

#should get 1
mean(spades)
```

